version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=bn_orangehrm
      - MARIADB_DATABASE=bitnami_orangehrm
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
    restart: always
  orangehrm:
    image: 'bitnami/orangehrm:latest'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - ORANGEHRM_DATABASE_USER=bn_orangehrm
      - ORANGEHRM_DATABASE_NAME=bitnami_orangehrm
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '8800:80'
      - '4430:443'
    depends_on:
      - mariadb
    volumes:
      - 'orangehrm_data:/bitnami'
    restart: always

volumes:
  mariadb_data:
    driver: local
  orangehrm_data:
    driver: local
